import React from "react";

// all the content of the page will not diplay at the same time after
// need to change state when use chooses and plan
const MyPlan = () => {
	return (
		<div className="container">
			<h2>Welcome autogenerated name lets set up this Budge plan</h2>
			<div className="idk">
				<h2>What do you have in mind when setting a target</h2>
				<select className="selectPlan" id="selectPlan">
					<option selected>Choose...</option>
					<option value="1">Travel</option>
					<option value="2">Debt Relief</option>
					<option value="3">Grow My Savings</option>
					<option value="4">Date Night</option>
					<option onClick={console.log("hello")} value="5">
						{/*prints out hello onload*/}
						Are chose to customize your own
					</option>
				</select>
			</div>
			<div>
				<h1>Great Job </h1>
				<h3>Here is what we need to know to get you started</h3>
				<input type="text" placeholder="How much debt do you have" />
				{/*some sort of mapping fucntion where the user can input
				mulitpule expenses list each one and have total displayed at the
                end which willl be stored and subtracted from income*/}
				<input type="text" placeholder="let add up you expenses" />
				what is your monthly income <input type="text" />
			</div>
		</div>
	);
};

export default MyPlan;
